### ISSUE TITLE
1.19-1.09 - Crash on single player world creation

### ISSUE THREAD

**Issue by MisterShawn** [LukeGrahamLandryMC/travel_anchors#4]
The crash happens as you're typing the name of the new world. Worked fine on joining a previously created world.

[Crash report](https://gist.github.com/quippen/406d68dfa0853de4e2eed10216e5dcd1)

**Comment by 0gp** [comment]
same in 1.18.2
https://pastebin.com/HSjTB1SQ

**Comment by LukeGrahamLandry** [comment]
ack pain. 
kinda funny bug tho, it sees you press space or shift while typing the world name, decides you’re clearly trying to teleport so it should check for anchors and stuff, then panics when it realizes theres no player yet. 
not actually hard to fix, shall get around to it sometime soon ish.
